version: '3.9'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '3002:80'
    depends_on:
      - api
    networks:
      - worm_network

  api:
    image: anhskohbo/birds-wormhole:latest
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      - redis
    ports:
      - '3000:3000'
    networks:
      - worm_network

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - worm_network

networks:
  worm_network:
    driver: bridge
